# Generated by Django 4.2 on 2023-04-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisacion_medica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medico',
            new_name='medicos',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='matrcula',
            new_name='matricula',
        ),
    ]
