# Generated by Django 4.2 on 2023-04-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisacion_medica', '0002_rename_medico_medicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisacion',
            name='datos_socio',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisacion',
            name='medico_rev',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
