# Generated by Django 4.2 on 2023-04-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisacion_medica', '0003_revisacion_datos_socio_revisacion_medico_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisacion',
            name='medico_rev',
        ),
        migrations.AddField(
            model_name='revisacion',
            name='datos_medico',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
